### Variables
@baseUrl = http://localhost:8000

### Comprobar que la API está funcionando
GET {{baseUrl}}/
Accept: application/json

### Crear un nuevo usuario
POST {{baseUrl}}/users/
Content-Type: application/json

{
  "username": "test_user",
  "email": "test@example.com",
  "password": "secure_password123",
  "is_active": true,
  "is_premium": false
}

### Obtener todos los usuarios
GET {{baseUrl}}/users/
Accept: application/json

### Obtener usuarios activos
GET {{baseUrl}}/users/?active=true
Accept: application/json

### Obtener usuarios premium
GET {{baseUrl}}/users/?premium=true
Accept: application/json

### Obtener un usuario específico (reemplazar {user_id} con un ID válido)
GET {{baseUrl}}/users/1
Accept: application/json

### Obtener usuario con sus tareas (reemplazar {user_id} con un ID válido)
GET {{baseUrl}}/users/1/details
Accept: application/json

### Actualizar un usuario (reemplazar {user_id} con un ID válido)
PUT